import type { Metadata } from 'next'
import Header from '@/components/layout-components/header'
import Hero from '@/components/layout-components/hero'
import Footer from '@/components/layout-components/footer'
import { getSession } from '@/server-actions/auth-actions'
import '../styles/global.css'
import { Inter as FontSans } from 'next/font/google'

import { cn } from '@/lib/utils'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  //TO DO - think of a better way to gain access to session data
  const session = await getSession()

  return (
    <html lang="en">
      <body>
        <div
          className={cn(
            'min-h-screen bg-background font-sans antialiased flex flex-col justify-between',
            fontSans.variable
          )}
        >
          <Header />
          <Hero userId={session.userId} />
          <div className="page-container">{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  )
}
